# Generated by Django 4.0.3 on 2022-04-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_alter_trader_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseitem',
            name='quantity_usd',
        ),
        migrations.AlterField(
            model_name='caseitem',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='trader.case'),
        ),
        migrations.CreateModel(
            name='CaseItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity_base_asset', models.FloatField()),
                ('sum_usd', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('case_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_orders', to='trader.caseitem')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
