# Generated by Django 4.0.4 on 2022-04-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_remove_caseitem_quantity_usd_alter_caseitem_case_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseitem',
            name='sum_usd',
        ),
        migrations.DeleteModel(
            name='CaseItemOrder',
        ),
    ]
