# Generated by Django 4.0.4 on 2022-04-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_remove_caseitem_sum_usd_delete_caseitemorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseitem',
            name='orders',
            field=models.TextField(blank=True, null=True),
        ),
    ]
