# Generated by Django 4.0.4 on 2022-04-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_caseitem_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseitem',
            name='orders',
            field=models.TextField(default='[]'),
        ),
    ]
