# Generated by Django 4.0.4 on 2022-04-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0010_caseitem_sum_in_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseitem',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
