# Generated by Django 4.0.4 on 2022-04-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0011_caseitem_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseitem',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
