# Generated by Django 4.0.4 on 2022-04-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0012_caseitem_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='fixed_profit',
            field=models.FloatField(default=0),
        ),
    ]
