# Generated by Django 4.0.4 on 2022-04-28 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0014_caseitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseitem',
            name='orders',
        ),
        migrations.CreateModel(
            name='FixedCaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField()),
                ('quantity_base_asset', models.FloatField()),
                ('profit', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_items', to='trader.case')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
